#!/usr/bin/env bash

# PORT_WWW isn't available at build time so we need to put it in postinstall
# this will take the nginx.conf.in template and replace the PORT_WWW variable with
# the PORT_WWW env variable.
sed > $HOME/nginx/conf/nginx.conf < /home/dotcloud/current/nginx.conf.in    \
    -e "s/@PORT_WWW@/${PORT_WWW:-42800}/g"